# Pengetahuan dasar untuk dibaca oleh script training LSTM
KNOWLEDGE_BASE = {
    "Anggur": "buah kecil berkelompok dengan rasa manis segar",
    "Anggur Biru": "varietas anggur berwarna gelap dengan kulit ungu tua",
    "Anggur Merah Muda": "anggur dengan warna kulit kemerahan yang manis",
    "Anggur Putih": "anggur dengan kulit hijau kekuningan yang segar",
    "Apel": "buah bulat renyah yang sangat populer",
    "Apel Braeburn": "apel dengan tekstur sangat keras dan rasa manis asam",
    "Apel Crimson Snow": "apel premium dengan daging buah putih bersih",
    "Apel Golden": "apel berkulit kuning dengan rasa manis madu",
    "Apel Granny Smith": "apel hijau dengan rasa asam yang tajam dan segar",
    "Apel Merah": "buah apel klasik berkulit merah dan renyah",
    "Apel Merah Delicious": "apel merah dengan bentuk khas dan rasa manis",
    "Apel Merah Kuning": "perpaduan apel warna merah dan kuning yang seimbang",
    "Apel Pink Lady": "apel merah muda dengan keseimbangan rasa manis asam",
    "Aprikot": "buah berbiji tunggal dengan kulit oranye beludru",
    "Akar Jahe": "rimpang tanaman dengan rasa pedas yang menghangatkan",
    "Almond": "kacang berbentuk lonjong dengan rasa gurih yang khas",
    "Alpukat": "buah berdaging mentega dengan lemak nabati tinggi",
    "Alpukat Hijau": "varietas alpukat dengan kulit hijau cerah",
    "Alpukat Hitam": "alpukat matang dengan kulit yang cenderung gelap",
    "Bawang": "umbi lapis untuk bumbu dapur dengan aroma tajam",
    "Bawang Merah": "bumbu dapur dengan warna ungu kemerahan",
    "Bawang Putih": "bumbu dapur dengan aroma sangat kuat dan khas",
    "Belimbing": "buah berbentuk bintang dengan rasa asam manis segar",
    "Berangan": "kacang pohon yang sering diolah dengan cara dipanggang",
    "Biji Mete": "kacang berbentuk ginjal yang gurih dan lembut",
    "Bit": "umbi berwarna merah pekat yang kaya akan nitrat",
    "Blackberry": "buah beri berwarna hitam dengan butiran kecil",
    "Blewah": "buah sejenis melon dengan aroma yang sangat harum",
    "Bluberi": "buah beri biru kecil yang kaya akan antioksidan",
    "Buah Ara": "buah manis dengan banyak biji kecil di dalamnya",
    "Buah Naga": "buah eksotis dengan kulit bersisik yang unik",
    "Buah Naga Hijau": "varietas buah naga dengan kulit berwarna hijau",
    "Buah Naga Merah": "buah naga dengan daging buah merah keunguan",
    "Buah Quince": "buah berbentuk pir yang harum namun keras",
    "Ceri": "buah merah kecil dengan tangkai panjang yang manis",
    "Ceri Asam": "varietas ceri yang sering digunakan untuk masakan",
    "Ceri Lilin": "buah ceri dengan permukaan kulit mengkilap seperti lilin",
    "Ceri Lilin Hitam": "ceri lilin dengan warna merah sangat gelap kehitaman",
    "Ceri Lilin Kuning": "ceri lilin berwarna kuning cerah yang manis",
    "Ceri Lilin Merah": "ceri lilin berwarna merah terang yang menggoda",
    "Ceri Rainier": "ceri premium berwarna kuning kemerahan yang sangat manis",
    "Ciplukan": "buah kecil berwarna kuning yang terbungkus kelopak",
    "Ciplukan Kulit": "buah ciplukan yang masih tertutup kulit pelindungnya",
    "Delima": "buah dengan ratusan biji merah permata di dalamnya",
    "Gooseberry": "buah beri kecil bergaris dengan rasa cenderung asam",
    "Granadilla": "varietas markisa dengan rasa yang sangat manis",
    "Hazelnut": "kacang bulat kecil yang sering digunakan untuk cokelat",
    "Huckleberry": "buah beri kecil yang mirip dengan bluberi",
    "Jagung": "bulir bijian kuning yang tersusun rapi pada tongkol",
    "Jagung Kulit": "tongkol jagung yang masih terbungkus pelepah hijau",
    "Jahe": "tanaman herbal pedas untuk kesehatan dan bumbu",
    "Jambu Biji": "buah tropis dengan banyak biji keras di dalamnya",
    "Jeruk": "buah sitrus populer kaya air dan menyegarkan",
    "Jeruk Bali": "jeruk berukuran sangat besar dengan bulir yang tebal",
    "Jeruk Clementine": "jeruk kecil tanpa biji yang sangat mudah dikupas",
    "Jeruk Mandarin": "jeruk berukuran sedang dengan rasa manis yang kuat",
    "Jeruk Nipis": "jeruk kecil hijau dengan rasa asam yang sangat kuat",
    "Jeruk Sitrus Merah Muda": "jeruk grapefruit dengan daging buah merah muda",
    "Jeruk Sitrus Putih": "jeruk grapefruit dengan daging buah putih kekuningan",
    "Jeruk Tangelo": "perpaduan antara jeruk mandarin dan grapefruit",
    "Kacang": "bijian kering yang menjadi sumber protein nabati",
    "Kacang Hutan": "berbagai jenis kacang yang tumbuh secara liar",
    "Kacang Kulit": "kacang tanah yang masih terbungkus cangkang keras",
    "Kacang Pekan": "kacang dengan tekstur renyah dan rasa sedikit manis",
    "Kelapa": "buah tropis dengan air segar dan daging putih",
    "Kembang Kol": "sayuran bunga berwarna putih yang padat",
    "Kenari": "kacang pohon dengan cangkang keras dan rasa gurih",
    "Kentang Merah": "umbi kentang dengan kulit berwarna merah",
    "Kentang Putih": "varietas kentang klasik untuk berbagai masakan",
    "Kesemek": "buah berwarna oranye yang terlihat seperti tomat",
    "Kiwi": "buah dengan kulit berbulu dan daging hijau segar",
    "Kol Rabi": "sayuran unik yang tumbuh dari batang yang membengkak",
    "Kubis Merah": "sayuran daun yang padat berwarna ungu tua",
    "Kubis Putih": "sayuran daun hijau pucat yang sangat padat",
    "Kumquats": "jeruk mungil yang bisa dimakan langsung dengan kulitnya",
    "Kurma": "buah gurun yang sangat manis dan kaya energi",
    "Leci": "buah tropis berkulit kasar dengan daging putih bening",
    "Lemon": "jeruk kuning cerah dengan rasa asam yang tajam",
    "Lemon Meyer": "perpaduan lemon dan jeruk yang lebih manis",
    "Mangga": "buah tropis berdaging kuning dengan aroma kuat",
    "Mangga Merah": "varietas mangga dengan gradasi warna merah pada kulit",
    "Manggis": "ratu buah dengan daging putih bersih yang sangat manis",
    "Markisa": "buah dengan isi bulir berlendir dan aroma harum",
    "Melon Madu": "melon dengan daging buah berwarna pucat yang sangat manis",
    "Melon Pepino": "buah unik perpaduan rasa melon dan mentimun",
    "Murbei": "buah beri panjang yang tumbuh pada pohon mulberry",
    "Nanas": "buah tropis bersisik dengan rasa asam manis segar",
    "Nanas Mini": "varietas nanas berukuran kecil yang sangat manis",
    "Nektarin": "buah sejenis persik namun memiliki kulit halus",
    "Nektarin Gepeng": "nektarin dengan bentuk pipih dan rasa sangat manis",
    "Paprika": "sayuran berbentuk lonceng dengan rasa tidak pedas",
    "Paprika Hijau": "paprika mentah dengan rasa sedikit getir dan renyah",
    "Paprika Kuning": "paprika dengan rasa yang lebih manis dari yang hijau",
    "Paprika Merah": "paprika matang dengan rasa paling manis",
    "Paprika Oranye": "paprika dengan warna cerah dan rasa yang lembut",
    "Pepaya": "buah tropis berdaging oranye yang baik untuk pencernaan",
    "Persik": "buah berbulu halus dengan aroma yang sangat harum",
    "Persik Gepeng": "varietas persik pipih yang populer di Asia",
    "Pir": "buah dengan tekstur daging yang sedikit berpasir",
    "Pir Abate": "pir dengan bentuk memanjang dan rasa yang manis",
    "Pir Batu": "varietas pir dengan tekstur daging yang sangat keras",
    "Pir Forelle": "pir kecil dengan bintik merah yang sangat cantik",
    "Pir Kaiser": "pir berkulit cokelat kasar dengan rasa yang khas",
    "Pir Merah": "varietas pir dengan kulit berwarna merah tua",
    "Pir Monster": "pir dengan ukuran yang sangat besar dari biasanya",
    "Pir Williams": "pir klasik yang sangat berair saat sudah matang",
    "Pisang": "buah kuning panjang yang kaya akan karbohidrat",
    "Pisang Ambon": "pisang meja populer dengan aroma yang sangat harum",
    "Pisang Merah": "varietas pisang unik dengan warna kulit merah",
    "Pistachio": "kacang berwarna hijau yang terlindungi cangkang",
    "Plum": "buah kecil berdaging lembut dengan rasa asam manis",
    "Polong Buncis": "sayuran berbentuk polong panjang yang renyah",
    "Potongan Stroberi": "irisan buah stroberi segar yang berwarna merah",
    "Rambutan": "buah tropis dengan kulit berambut dan daging manis",
    "Rasberi": "buah beri merah dengan rongga di tengahnya",
    "Redcurrant": "buah beri merah kecil yang tumbuh berkelompok",
    "Salak": "buah eksotis dengan kulit bersisik cokelat seperti ular",
    "Semangka": "buah besar kaya air dengan daging merah segar",
    "Sirsak Srikaya": "buah berdaging putih dengan rasa asam manis unik",
    "Stroberi": "buah beri merah berbintik dengan aroma harum",
    "Terong": "sayuran berbentuk lonjong biasanya berwarna ungu",
    "Terong Belanda": "buah berbentuk telur dengan rasa asam yang khas",
    "Terong Panjang": "varietas terong dengan bentuk yang sangat panjang",
    "Timun": "sayuran kaya air yang sangat menyegarkan",
    "Timun Jepang": "mentimun dengan kulit hijau gelap dan rasa lebih manis",
    "Tomat": "buah merah yang sering digunakan sebagai sayuran",
    "Tomat Ceri Kuning": "tomat kecil seukuran ceri berwarna kuning",
    "Tomat Ceri Marun": "tomat ceri dengan warna merah gelap kecokelatan",
    "Tomat Ceri Merah": "tomat kecil yang sangat manis dan renyah",
    "Tomat Ceri Oranye": "tomat ceri dengan warna oranye cerah",
    "Tomat Jantung": "tomat berukuran besar dengan bentuk mirip jantung",
    "Tomat Kuning": "varietas tomat dengan warna kulit kuning cerah",
    "Tomat Marun": "tomat besar dengan warna merah yang sangat pekat",
    "Ubi Jalar": "umbi manis yang kaya akan vitamin dan energi",
    "Wortel": "sayuran akar berwarna oranye yang baik untuk mata",
    "Zukini Gelap": "sayuran mirip mentimun dengan warna hijau sangat tua",
    "Zukini Hijau": "labu musim panas yang sangat populer di masakan barat",
}

VITAMIN_BASE = {
    "Anggur": "C dan K",
    "Apel": "A dan C",
    "Aprikot": "A dan E",
    "Alpukat": "E dan K",
    "Bawang": "C dan B6",
    "Belimbing": "C dan Serat",
    "Bit": "C dan B9",
    "Blackberry": "C dan K",
    "Bluberi": "C dan K",
    "Buah Naga": "C dan B2",
    "Ceri": "C dan A",
    "Ciplukan": "A dan C",
    "Delima": "C dan K",
    "Jagung": "B1 dan B5",
    "Jahe": "B3 dan C",
    "Jambu Biji": "C Tinggi",
    "Jeruk": "C dan Antioksidan",
    "Kacang": "E dan B1",
    "Kelapa": "B dan Kalium",
    "Kembang Kol": "C dan K",
    "Kentang": "C dan B6",
    "Kiwi": "C dan K",
    "Kubis": "K dan C",
    "Kurma": "B6 dan Serat",
    "Lemon": "C dan Flavonoid",
    "Mangga": "A dan C",
    "Manggis": "C dan B2",
    "Markisa": "A dan C",
    "Melon": "A dan C",
    "Nanas": "C dan B1",
    "Nektarin": "A dan C",
    "Paprika": "C dan B6",
    "Pepaya": "C dan A",
    "Persik": "A dan C",
    "Pir": "C dan K",
    "Pisang": "B6 dan C",
    "Rambutan": "C dan Zat Besi",
    "Rasberi": "C dan E",
    "Salak": "C dan Serat",
    "Semangka": "A dan C",
    "Stroberi": "C dan B9",
    "Terong": "K dan B6",
    "Timun": "K dan C",
    "Tomat": "C dan K",
    "Wortel": "A dan K",
    "Zukini": "A dan C",
}